language: node_js
node_js:
  - '10.5.0'
cache:
  directories:
    - 'node_modules'
    - 'client/node_modules'
before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
install:
  - 'npm i -D'
  - 'npm run heroku-postbuild'
script:
  - 'npm run test:coverage'
after_success:
  - 'npm run coverage'
