language: node_js
node_js:
  - "12.13.0"
cache:
  directories:
    - "node_modules"

env:
  - MONGODB=4.0.0

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - mongo --version
  - npm run init

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath
    ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath
    ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork
  - npm run build
  - npm run database:build:dev --prefix server
  - mongo --version

script:
  - "npm run test-coverage"

after_success:
  - "npm run coverage"

after_script:
  - pkill mongod
