export const appColors = {
  BLACK: '#000',
  NEAR_BLACK: '#111',
  DARK_GRAY: '#333',
  MID_GRAY: '#555',
  GRAY: '#777',
  LIGHT_GRAY: '#aaa',
  WHITE: '#f4f4f4',
  DARK_RED: '#e7040f',
  RED: '#ff4136',
  LIGHT_RED: '#ff725c',
  ORANGE: '#ff6300',
  GOLD: '#ffb700',
  YELLOW: '#ffd700',
  LIGHT_YELLOW: '#fbf1a9',
  PURPLE: '#5e2ca5',
  LIGHT_PURPLE: '#a463f2',
  DARK_PINK: '#d5008f',
  PINK: '#ff41b4',
  LIGHT_PINK: '#ff80cc',
  DARK_GREEN: '#137752',
  GREEN: '#19a974',
  LIGHT_GREEN: '#9eebcf',
  NAVY: '#001b44',
  DARK_BLUE: '#00449e',
  BLUE: '#357edd',
  LIGHT_BLUE: '#96ccff',
};

export const useClassColor = {
  A1: appColors.LIGHT_PINK,
  A3: appColors.LIGHT_GREEN,
  B1: appColors.LIGHT_BLUE,
  B2: appColors.LIGHT_YELLOW,
  B8: appColors.GOLD,
  D1: appColors.LIGHT_PURPLE,
  D2: appColors.ORANGE,
  Other: appColors.WHITE,
};

export const userRoleColor = {
  user: appColors.GREEN,
  superUser: appColors.PINK,
  admin: appColors.GOLD,
};
